name: Tests action for CI

on: [push, pull_request]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run grumphp
      run: composer run-script test
